version: "2"         #  required to adjust maintainability checks

plugins:
  eslint:
    enabled: false
checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 6
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 7
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 5
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
