version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8-jessie-browsers-legacy
    working_directory: ~/fww-web
  #  environment:
  #    CC_TEST_REPORTER_ID: 4e3f216ef04f652fcf6f1e073aeeb12b3f209429adfcd75d4e0cb94f76a9edeb	

    steps:
      - checkout
      - run: echo "Welcome to FFW web deploy"     

      - run: npm install

      - run: # run tests test-results/coverage/jest
          name: Run jest tests
          command: |
            mkdir -p test-results
            
      - run:
          name: Setup Code Climate test-reporter
          command: |
                  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                  chmod +x ./cc-test-reporter

      - run:
          name: Code Coverage
          command: |
                  ./cc-test-reporter before-build
                   npm run test:covout || true
                   
                  ./cc-test-reporter after-build -t lcov -p /home/circleci/fww-web --exit-code $?

  hold:
    docker:
      - image: circleci/node:8-jessie-browsers-legacy
    working_directory: ~/fww-web
    steps:
      - run: echo "buildtriggered by ${CIRCLE_USERNAME}"    
            
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - hold: 
            type: approval
            requires:
                - build
            filters:
                branches:
                    only : development
                  #  ignore:
                   #     - /.*-R1/
                    #only:
                    #    - /.*-R1/
 

#version: 2.1
#commands:
#  deploy_steps:
#    parameters:
#    compare_host:
#      type: string
#      
#    steps:
#      - run:
#          name: Snapshot database
#          command: echo << parameters.compare_host >>  $APP_ENVIRONMENT
#
#jobs:
#  build:
#    docker:
#      - image: circleci/node:8-jessie-browsers-legacy
#      
#    working_directory: ~/fww-web
#    environment:
#
#      - APP_ENVIRONMENT: 'experimental' 
#    steps:
#      - checkout
#      - run: echo "Welcome to FFW web deploy"
#      - deploy_steps:
#          compare_host: successs
#      - run:
#          name: Print npm version
#          command:  |
#            pwd
#            npm -v
#            echo test "<< parameters.should_build >>"        
#
#      - run: npm install
#    
#      - type: cache-save
#        name: Store/update package cache
#        key: fww-web-dependencies-{{ checksum "package.json" }}
#        paths:
#          - node_modules
#          
#      - run: # run tests
#          name: Run jest tests
#          command: |
#            mkdir -p test-results
#            
#            npm run test
#      - run:
#          name: Run javascript linter
#          command: |
#            npm run lint && echo "++Linting Completed ${result}++"            
#            npm run format
#       
#
#  deploy_dev: 
#    docker:
#      - image: circleci/node:8-jessie-browsers-legacy
#    working_directory: ~/fww-web
#
#      
#    steps:
#      #build reactjs code and deploy 
#      #- run: npm run build
#      - checkout
#      - run: 
#          command: |
#            whoami
#            ls
#            echo "${aws_access_key_id}"
#            
#      - run: sudo apt-get update && sudo apt-get install -y python-dev
#      - run: curl -O https://bootstrap.pypa.io/get-pip.py
#      - run: sudo python get-pip.py
#      - run: sudo pip install awscli --upgrade  
#      - run: aws --version
#      #- run: 
#      #    name: S3 web deploy
#      #    command: AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" aws s3 sync build/ s3://k8sasv --delete          
#
#        
#workflows:
#  version: 2
#  build_accept_deploy:
#    jobs:
#      - build
##      - deploy_dev:
##          requires:
##            - build
##          filters:
##            branches:
##              only: development  
#

