version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: echo "Welcome to FFW"
      - run:
          name: Print date
          command:  |
            date
            npm -v
