version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
      
    working_directory: ~/fww-web
    steps:
      - checkout
      - run: echo "Welcome to FFW web deploy"
      - run:
          name: Print npm version
          command:  |
            pwd
            npm -v
                     
      - restore_cache:
          keys: fww-web-dependencies-{{ checksum "package.json" }}
          name: Restore packege cache
          
      - run: npm install
  
      - type: cache-save
        name: Store/update package cache
        key: fww-web-dependencies-{{ checksum "package.json" }}
        paths:
          - node_modules
          
      - run: # run tests
          name: Run jest tests
          command: npm run test
      - run:
          name: Run javascript linter
          command: |
            npm run lint --format junit --output-file ./output/coverage/junit/eslint.xml && echo "Linting Completed"            
            npm run format
