version: 2.1

jobs: # conditional steps may also be defined in `commands:`
  job_with_optional_custom_checkout:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/fww-services
    parameters:
      custom_checkout:
        type: string
        default: ""
    steps:
      - run: echo <<parameters.custom_checkout>>
      - checkout
      - run: 
         name:
         command: |
                uname -a & uname -r
                sudo apt-get install mailutils -y
                echo "+++++++++++"
                sudo sleep 10
                pwd
                ls -la
                echo "++sending mail++"
                echo "Test attachement " | mail -s "Subject Here" venkatamahesha@virtusa.com -A ./test.txt

workflows:
  build-test-deploy:
    jobs:
      - job_with_optional_custom_checkout:
          custom_checkout: "any non-empty string is truthy"





#version: 2.1
#commands:
#  deploy_steps:
#    parameters:
#    compare_host:
#      type: string
#      
#    steps:
#      - run:
#          name: Snapshot database
#          command: echo << parameters.compare_host >>  $APP_ENVIRONMENT
#
#jobs:
#  build:
#    docker:
#      - image: circleci/node:8-jessie-browsers-legacy
#      
#    working_directory: ~/fww-web
#    environment:
#
#      - APP_ENVIRONMENT: 'experimental' 
#    steps:
#      - checkout
#      - run: echo "Welcome to FFW web deploy"
#      - deploy_steps:
#          compare_host: successs
#      - run:
#          name: Print npm version
#          command:  |
#            pwd
#            npm -v
#            echo test "<< parameters.should_build >>"        
#
#      - run: npm install
#    
#      - type: cache-save
#        name: Store/update package cache
#        key: fww-web-dependencies-{{ checksum "package.json" }}
#        paths:
#          - node_modules
#          
#      - run: # run tests
#          name: Run jest tests
#          command: |
#            mkdir -p test-results
#            
#            npm run test
#      - run:
#          name: Run javascript linter
#          command: |
#            npm run lint && echo "++Linting Completed ${result}++"            
#            npm run format
#       
#
#  deploy_dev: 
#    docker:
#      - image: circleci/node:8-jessie-browsers-legacy
#    working_directory: ~/fww-web
#
#      
#    steps:
#      #build reactjs code and deploy 
#      #- run: npm run build
#      - checkout
#      - run: 
#          command: |
#            whoami
#            ls
#            echo "${aws_access_key_id}"
#            
#      - run: sudo apt-get update && sudo apt-get install -y python-dev
#      - run: curl -O https://bootstrap.pypa.io/get-pip.py
#      - run: sudo python get-pip.py
#      - run: sudo pip install awscli --upgrade  
#      - run: aws --version
#      #- run: 
#      #    name: S3 web deploy
#      #    command: AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" aws s3 sync build/ s3://k8sasv --delete          
#
#        
#workflows:
#  version: 2
#  build_accept_deploy:
#    jobs:
#      - build
##      - deploy_dev:
##          requires:
##            - build
##          filters:
##            branches:
##              only: development  
#
