version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-jessie-browsers-legacy
    working_directory: ~/fww-web
    steps:
      - checkout
      - run: echo "Welcome to FFW"
      - run:
          name: Print date
          command:  |
            ls ~/fww-web
            npm -v
      - restore_cache:
          keys: fww-web-dependencies-{{ checksum "package.json" }}
          name: Restore packege cache
          
      - run: npm install
      
      - type: cache-save
        name: Store/update package cache
        key: fww-web-dependencies-{{ checksum "package.lock" }}
        paths:
          - node_modules
      
