version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    
    working_directory: ~/fww-web
    
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: Print npm version
           command:  |
              date
              npm -v
              ls 
              pwd
