version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-jessie-browsers-legacy
      
    working_directory: ~/fww-web
    steps:
      - checkout
      - run: echo "Welcome to FFW web deploy"
      - run:
          name: Print npm version
          command:  |
            pwd
            npm -v
                     
      - restore_cache:
          keys: fww-web-dependencies-{{ checksum "package.json" }}
          name: Restore packege cache
          
      - run: npm install
  
      - type: cache-save
        name: Store/update package cache
        key: fww-web-dependencies-{{ checksum "package.json" }}
        paths:
          - node_modules
          
      - run: # run tests
          name: Run jest tests
          command: |
            mkdir -p test-results
            
            npm run test
      - run:
          name: Run javascript linter
          command: |
            npm run lint && echo "++Linting Completed++"            
            npm run format
        
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          
  deploy_dev:
    docker:
      - image: circleci/node:8-jessie-browsers-legacy
    working_directory: ~/fww-web
    steps:
      - run: 
          command: |
            aws --version
            
            
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - deploy_dev:
          requires:
            - build
