version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-jessie-browsers-legacy
    working_directory: ~/fww-web
    steps:
      - checkout
      - run: echo "Welcome to FFW"
      - run:
          name: Print date
          command:  |
            ls ~/fww-web
            npm -v
